### ISSUE TITLE
unknown type name 'uint'; did you mean 'int'? using clang++

### ISSUE THREAD

**Issue by kkweon** [Dobiasd/FunctionalPlus#80] opened 2017-08-14 08:20 UTC
- [Problem](#sec-1)
  - [First Error](#sec-1-1)
  - [Second Error](#sec-1-2)
  - [Third Error (same as second)](#sec-1-3)
- [What I did](#sec-2)
- [My setup](#sec-3)

# Problem<a id="sec-1"></a>

Thanks for the awesome library first of all.
During compilation, I get the following error messages.

Please let me know if you need more information. 

Thank you.

## First Error<a id="sec-1-1"></a>

    /usr/local/include/fplus/composition.hpp:385:29: error: unknown type name 'uint'; did you mean 'int'?

## Second Error<a id="sec-1-2"></a>

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:668:78: error: implicit instantiation of
          undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        _LIBCPP_INLINE_VISIBILITY back_insert_iterator& operator=(const typename _Container::value_type& __value_)

## Third Error (same as second)<a id="sec-1-3"></a>

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:671:72: error: implicit instantiation of
          undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        _LIBCPP_INLINE_VISIBILITY back_insert_iterator& operator=(typename _Container::value_type&& __value_)

# What I did<a id="sec-2"></a>

-   Using cmake

```bash
git clone https://github.com/Dobiasd/FunctionalPlus
cd FunctionalPlus
mkdir build
cd build
cmake ..
sudo make install
```

-   Save the tutorial code as main.cpp

```c++
#include <fplus/fplus.hpp>
#include <iostream>

int main() {
  std::list<std::string> things = {"same old", "same old"};
  if (fplus::all_the_same(things))
    std::cout << "All things being equal." << std::endl;
}
```

-   Compile

```bash
clang++ -std=c++14 main.cpp
```

-   Results:

```
In file included from main.cpp:1:
In file included from /usr/local/include/fplus/fplus.hpp:10:
/usr/local/include/fplus/composition.hpp:385:29: error: unknown type name 'uint'; did you mean 'int'?
        return [f, storage](uint x)
                            ^
In file included from main.cpp:1:
In file included from /usr/local/include/fplus/fplus.hpp:9:
In file included from /usr/local/include/fplus/compare.hpp:9:
In file included from /usr/local/include/fplus/function_traits.hpp:25:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:477:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:668:78: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    _LIBCPP_INLINE_VISIBILITY back_insert_iterator& operator=(const typename _Container::value_type& __value_)
                                                                             ^
/usr/local/include/fplus/container_common.hpp:111:16: note: in instantiation of template class 'std::__1::back_insert_iterator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >' requested here
        return std::back_inserter(ys);
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
In file included from main.cpp:1:
In file included from /usr/local/include/fplus/fplus.hpp:9:
In file included from /usr/local/include/fplus/compare.hpp:9:
In file included from /usr/local/include/fplus/function_traits.hpp:25:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:477:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:671:72: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    _LIBCPP_INLINE_VISIBILITY back_insert_iterator& operator=(typename _Container::value_type&& __value_)
                                                                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
3 errors generated.
```

# My setup<a id="sec-3"></a>

-   OSX
-   clang(++)

```bash
clang++ --version
```

    Apple LLVM version 8.1.0 (clang-802.0.42)
    Target: x86_64-apple-darwin16.7.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by Dobiasd** [comment] 2017-08-14 08:51
Thank you for this very good bug report.

Your example does not use memoization at all, but the error is located in `internal::memoize_recursive_helper`.

Up to now I was unable to reproduce the problem, but one thing in the code looked like an obvious error to me, that likely is the cause for this. It is fixed in [this commit](https://github.com/Dobiasd/FunctionalPlus/commit/e9cc80f08d9f9a3d2d3b0040fee45bb3007fb387).

Could you please pull and install again and let me know it the new version fixes your problem?

**Comment by kkweon** [comment] 2017-08-14 09:59
Thanks!! The first error is gone.
What should I do with the second error: 

      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'?

```
$ clang++ -std=c++1z main.cpp
```
```
In file included from main.cpp:1:
In file included from /usr/local/include/fplus/fplus.hpp:9:
In file included from /usr/local/include/fplus/compare.hpp:9:
In file included from /usr/local/include/fplus/function_traits.hpp:25:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:477:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:668:78: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
  ...back_insert_iterator& operator=(const typename _Container::value_type& _...
                                                    ^
/usr/local/include/fplus/container_common.hpp:111:16: note: in instantiation of
      template class
      'std::__1::back_insert_iterator<std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> > >' requested here
        return std::back_inserter(ys);
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: 
      template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
In file included from main.cpp:1:
In file included from /usr/local/include/fplus/fplus.hpp:9:
In file included from /usr/local/include/fplus/compare.hpp:9:
In file included from /usr/local/include/fplus/function_traits.hpp:25:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:477:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:671:72: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    _LIBCPP_INLINE_VISIBILITY back_insert_iterator& operator=(typename _Cont...
                                                                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: 
      template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
```

**Comment by Dobiasd** [comment] 2017-08-14 10:10
Could you please try out if the following code compiles in your environment?

```cpp
#include <string>
int main()
{
    std::string str;
    std::back_inserter(str);
}
```

**Comment by kkweon** [comment] 2017-08-14 10:13
```bash
clang++ string_check.cpp -o check_str
./check_str
```
it compiles without an error

**Comment by kkweon** [comment] 2017-08-14 10:16
It's the clang that is causing this error though I'm not certain.
Do you think so?
I don't get any error with `g++`

**Comment by Dobiasd** [comment] 2017-08-14 10:31
Yes, I also guess it has something to do with your clang installation, since [clang usually seems to work fine for this](https://travis-ci.org/Dobiasd/FunctionalPlus).

But I would like to isolate the problem. It would help to make sure there really is not an error in FunctionalPlus. And also it would help you find out what is going on with your clang installation and perhaps point to a way to a cure.

I see you sometimes compile with `-std=c++14`, sometimes with `-std=c++1z` and sometimes without.

Could you please check if this code compiles with `clang++ -std=c++14`?

```cpp
#include <string>
int main()
{
    std::string str;
    std::back_inserter(str);
    typedef std::string::value_type T;
}
```

**Comment by kkweon** [comment] 2017-08-14 10:40
Sorry about that. I wanted to see if that was the problem, but guess not

- Save to str_check.cpp
``` C++
#include <string>
int main()
{
    std::string str;
    std::back_inserter(str);
    typedef std::string::value_type T;
}
```

```bash
clang++ -std=c++14 str_check.cpp -o check_str
./check_str
echo "done"
```

    done

```bash
clang++ -std=c++1z str_check.cpp -o check_str
./check_str
echo "done"
```

    done

```bash
clang++ str_check.cpp -o check_str
./check_str
echo "done"
```

    done

**Comment by Dobiasd** [comment] 2017-08-14 10:57
Interesting, thanks.

Could you please try out another one using `clang++ -std=c++14`?

If this method is too cumbersome to you, please let me know.

```cpp
#include <iterator>
#include <iostream>
#include <string>
int main()
{
    std::string str = "a";
    auto it = std::back_inserter(str);
    *it = 'b';
    std::cout << str << std::endl;
}
```

**Comment by kkweon** [comment] 2017-08-14 11:03
It's totally fine! No error again.

```bash
rm -rf third_test
clang++ -std=c++14 third_test.cpp -o third_test && echo "done"
./third_test
```

    done
    ab

```bash
rm -rf third_test
clang++ -std=c++1z third_test.cpp -o third_test && echo "done"
./third_test
```

    done
    ab

```bash
rm -rf third_test
clang++ third_test.cpp -o third_test && echo "done"
./third_test
```

    done
    ab

**Comment by Dobiasd** [comment] 2017-08-14 11:04
Oh, I think I got it. I simply forgot to "#include <string>" at the appropriate place. [This commit](https://github.com/Dobiasd/FunctionalPlus/commit/56255dd543b430ae98b0d1c67fb7d0920981d7e1) corrects it.

Could you please pull and install again and let me know about the result?

**Comment by kkweon** [comment] 2017-08-14 11:07
Finally! Thank you so much for your help!

```bash
rm -rf main
clang++ -std=c++14 main.cpp -o main && echo "Done"
./main
```

    Done
    All things being equal.

**Comment by Dobiasd** [comment] 2017-08-14 11:08
Thank you very much too!

Help like you provided today is invaluable for improving the quality of a library like this.

**Closed by Dobiasd** 2017-08-14 11:08 UTC
